### PR TITLE
feat: automatically change domain to ip

### PR DESCRIPTION
**Pull request by NImaism**
**This pull request adds support for domain names in the readInput function. Previously, the function only supported IP addresses as input. With this change, the function can now resolve domain names to IP addresses using the net.LookupIP function.**

**In addition to adding support for domain names, the code has been refactored to improve readability and reduce code duplication. The IP validation logic has been moved into a separate function that can be reused in multiple places, and errors returned by the os.ReadFile and net.LookupIP functions are now checked and returned to the caller.**

**Overall, this is a useful feature that improves the functionality of the readInput function. The code changes have been reviewed and tested, and everything looks good to me.**

**I'm very happy to have contributed to this project and improved the functionality of the readInput function by adding support for domain names. 😀**

### CODE REVIEW

**Comment by ImAyrix** [comment]
Hi Nima,

thank you for taking the time to make the cut-cdn more complete, but it seems like there is a problem with your code. The issue is that cut-cdn only checks version 4 IPs and not version 6. As a result, your changes will produce incorrect output. Please try to address this issue in your code.

Screenshot from 2023-06-29 12-54-55

Best regards,
Ayrix

**Comment by NImaism** [comment]
**Thanks for letting me know, Amirabbas! I can modify the code to support IPv6 or disable it in ReadInput if it's not necessary for the project** 👍

**Comment by ImAyrix** [comment]
I have decided to postpone the implementation of IP version 6 for now. It is not necessary at the moment, so it would be better to remove it from the input reading function temporarily.

Thank you and best wishes to you.

**Comment by NImaism** [comment]
Thank you for informing me of your decision to postpone the implementation of IP version 6. I fully understand your reasoning and have temporarily removed the code for reading IPv6 addresses from the input function.

I appreciate your cooperation and wish you all the best. 💯

**Comment by ImAyrix** [comment]
Your work was excellent.
To make the final correction, I would like to mention that checking if the input is a domain should be done as the last step. This means that if we have a file with the name ayrix.info, it should be given priority. Only if the input is neither an IP nor a file, then we should check whether it is a domain or not.

**Comment by ImAyrix** [comment]
Hi Nima,
I wanted to thank you for your efforts in making the "cut-cdn" more complete. Thank you very much. I wish you all the best.

**Pull request merged**
